/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Controladores.ControladorTareas;
import Logica.DataTypes.DataTarea;
import Logica.DataTypes.DataTipoArticulo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class AltaTareas extends javax.swing.JInternalFrame implements ListSelectionListener {

    /**
     * Creates new form AltaTareas
     */
    private final ArrayList<DataTipoArticulo> tipoArticulos;
    private ControladorTareas CT = ControladorTareas.getInstance();
    private DataTipoArticulo tArtSeleccionado = null;
    
    public AltaTareas() {
        initComponents();
        tipoArticulos = (ArrayList<DataTipoArticulo>) CT.darTipoArticulos();
        cargarTipoArticulos(tipoArticulos, "");
        TableTipoArt.getSelectionModel().addListSelectionListener(this);
    }
    
    
    private void cargarTipoArticulos(ArrayList<DataTipoArticulo> dtcs, String filtro) {
        // Obtiene el modelo de la tablaClientes y borra su contenido
        DefaultTableModel dtm = (DefaultTableModel) TableTipoArt.getModel();
        dtm.setRowCount(0);

        // Agrega los clientes a la tablaClientes
        for (DataTipoArticulo dtA : dtcs) {
            if (dtA.getNombre().contains(filtro)) {
                Object[] data = {
                    dtA
                };
                dtm.addRow(data);
            }
        }
    }
    
    
    @Override
    public void valueChanged(ListSelectionEvent e) {
        // Obtiene el nombre del del tipo de articulo seleccionado
        if (TableTipoArt.getSelectedRow() != -1){
            tipoArticuloSelecionado((DataTipoArticulo) TableTipoArt.getValueAt(TableTipoArt.getSelectedRow(), 0), "");
        }
    
    }
    
    private void tipoArticuloSelecionado(DataTipoArticulo dtTA, String filtro) {        
        
                 
            tArtSeleccionado = dtTA;
            List<DataTarea> tareas = CT.darTareasCodTA(dtTA.getId());
                
            DefaultTableModel dtt = (DefaultTableModel) TableTareas.getModel();
            dtt.setRowCount(0);

            for (DataTarea t : tareas) {
                Object[] data = {
                        t.getNombre(), t.getDescripcion(),};
                    dtt.addRow(data);

            }       
        
    }  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTipoArt = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTipoArt = new javax.swing.JTable();
        jPanelTareas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableTareas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblNombreTarea = new javax.swing.JLabel();
        lblNombreTarea1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescpricon = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanelTipoArt.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos de articulos"));

        TableTipoArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane1.setViewportView(TableTipoArt);

        javax.swing.GroupLayout jPanelTipoArtLayout = new javax.swing.GroupLayout(jPanelTipoArt);
        jPanelTipoArt.setLayout(jPanelTipoArtLayout);
        jPanelTipoArtLayout.setHorizontalGroup(
            jPanelTipoArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoArtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
        );
        jPanelTipoArtLayout.setVerticalGroup(
            jPanelTipoArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoArtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
        );

        jPanelTareas.setBorder(javax.swing.BorderFactory.createTitledBorder("Tareas"));

        TableTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(TableTareas);

        javax.swing.GroupLayout jPanelTareasLayout = new javax.swing.GroupLayout(jPanelTareas);
        jPanelTareas.setLayout(jPanelTareasLayout);
        jPanelTareasLayout.setHorizontalGroup(
            jPanelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanelTareasLayout.setVerticalGroup(
            jPanelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTareasLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Tarea"));

        lblNombreTarea.setText("Nombre");

        lblNombreTarea1.setText("Descripcion");

        txtDescpricon.setColumns(20);
        txtDescpricon.setRows(5);
        jScrollPane3.setViewportView(txtDescpricon);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreTarea1)
                    .addComponent(lblNombreTarea))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(80, 80, 80)
                        .addComponent(btnCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(jScrollPane3))
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTarea)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreTarea1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnCancelar))
                        .addGap(6, 6, 6))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTipoArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTipoArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        
        if (TableTipoArt.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de Articulo:\n");
            return;
        }
        
        
        //CT.AltaTarea(tar);
        double tiempo = 30.0;
        DataTarea t = new DataTarea(null, txtNombre.getText(), txtDescpricon.getText(), tiempo);
       
        CT.AltaTarea(t, tArtSeleccionado.getId());
                
        javax.swing.JOptionPane.showMessageDialog(null, "La nueva tarea se ingresado con exito", "Felicitaciones!", JOptionPane.INFORMATION_MESSAGE);
        
        txtNombre.setText("");
        txtDescpricon.setText("");
        
        TableTipoArt.clearSelection();       
        
        DefaultTableModel tt = (DefaultTableModel) TableTareas.getModel();
        tt.setRowCount(0);
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableTareas;
    private javax.swing.JTable TableTipoArt;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTareas;
    private javax.swing.JPanel jPanelTipoArt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNombreTarea;
    private javax.swing.JLabel lblNombreTarea1;
    private javax.swing.JTextArea txtDescpricon;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
