/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author Diego
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void centrar(JInternalFrame cpc) {
        Dimension desktopSize = this.getSize();
        Dimension jInternalFrameSize = cpc.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        cpc.setLocation(width, height - 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AltaPersona = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        AgregarTarea = new javax.swing.JMenuItem();
        Relaciones = new javax.swing.JMenu();
        jRelacionesItem1 = new javax.swing.JMenuItem();
        jMenuItemAltaRec = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Registro");

        AltaPersona.setText("AltaPersona");
        AltaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaPersonaActionPerformed(evt);
            }
        });
        jMenu1.add(AltaPersona);

        jMenuItem1.setText("AltaTipoArticulo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        AgregarTarea.setText("Agregar Tarea");
        AgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarTareaActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarTarea);

        jMenuBar1.add(jMenu1);

        Relaciones.setText("Relaciones");

        jRelacionesItem1.setText("Alta Tecnicos Capacitados");
        jRelacionesItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelacionesItem1ActionPerformed(evt);
            }
        });
        Relaciones.add(jRelacionesItem1);

        jMenuItemAltaRec.setText("AltaReclamos");
        jMenuItemAltaRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaRecActionPerformed(evt);
            }
        });
        Relaciones.add(jMenuItemAltaRec);

        jMenuBar1.add(Relaciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaPersonaActionPerformed
        // TODO add your handling code here:
        AltaPersona p = new AltaPersona();
        PanelMenu.add(p);
        centrar(p);
        p.show();
        
    }//GEN-LAST:event_AltaPersonaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AltaTipoArticulo tp = new AltaTipoArticulo();
        PanelMenu.add(tp);
        centrar(tp);
        tp.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void AgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarTareaActionPerformed
        // TODO add your handling code here:
        AltaTareas aTarea = new AltaTareas();
        PanelMenu.add(aTarea);
        centrar(aTarea);
        aTarea.show();
    }//GEN-LAST:event_AgregarTareaActionPerformed

    private void jRelacionesItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelacionesItem1ActionPerformed
        // TODO add your handling code here:
        AltaTecnicosCapacitados altaTecCap = new AltaTecnicosCapacitados();
        PanelMenu.add(altaTecCap);
        centrar(altaTecCap);
        altaTecCap.show();
    }//GEN-LAST:event_jRelacionesItem1ActionPerformed

    private void jMenuItemAltaRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaRecActionPerformed
        // TODO add your handling code here:
        AltaReclamos altaRec = new AltaReclamos();
        PanelMenu.add(altaRec);
        centrar(altaRec);
        altaRec.show();
    }//GEN-LAST:event_jMenuItemAltaRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarTarea;
    private javax.swing.JMenuItem AltaPersona;
    private javax.swing.JDesktopPane PanelMenu;
    private javax.swing.JMenu Relaciones;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAltaRec;
    private javax.swing.JMenuItem jRelacionesItem1;
    // End of variables declaration//GEN-END:variables
}
